FROM golang:1.23-alpine

WORKDIR /app

# Copy the source code
COPY protobuff/* protobuff/

# Copy the source code
COPY server/* server/

WORKDIR /app/server

# Download dependencies
RUN go mod download

# Build the client
RUN go build -o server server.go

EXPOSE 50051

CMD ["./server"] 