version: '3.8'

services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"
    networks:
      - grpc-network

  grpc-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - grpc-server
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge 