FROM golang:1.23-alpine

WORKDIR /app

# Copy the source code
COPY protobuff/* protobuff/

# Copy the source code
COPY client/* client/

WORKDIR /app/client

# Download dependencies
RUN go mod download

# Build the client
RUN go build -o client client.go

# Wait for server to be ready and then run client
CMD ["./client"] 