// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: contract.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomCalculator_Calculate_FullMethodName = "/myservice.CustomCalculator/Calculate"
	CustomCalculator_Multiply_FullMethodName  = "/myservice.CustomCalculator/Multiply"
)

// CustomCalculatorClient is the client API for CustomCalculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomCalculatorClient interface {
	Calculate(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
	Multiply(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error)
}

type customCalculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomCalculatorClient(cc grpc.ClientConnInterface) CustomCalculatorClient {
	return &customCalculatorClient{cc}
}

func (c *customCalculatorClient) Calculate(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Output)
	err := c.cc.Invoke(ctx, CustomCalculator_Calculate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customCalculatorClient) Multiply(ctx context.Context, in *Input, opts ...grpc.CallOption) (*Output, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Output)
	err := c.cc.Invoke(ctx, CustomCalculator_Multiply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomCalculatorServer is the server API for CustomCalculator service.
// All implementations must embed UnimplementedCustomCalculatorServer
// for forward compatibility.
type CustomCalculatorServer interface {
	Calculate(context.Context, *Input) (*Output, error)
	Multiply(context.Context, *Input) (*Output, error)
	mustEmbedUnimplementedCustomCalculatorServer()
}

// UnimplementedCustomCalculatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomCalculatorServer struct{}

func (UnimplementedCustomCalculatorServer) Calculate(context.Context, *Input) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedCustomCalculatorServer) Multiply(context.Context, *Input) (*Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (UnimplementedCustomCalculatorServer) mustEmbedUnimplementedCustomCalculatorServer() {}
func (UnimplementedCustomCalculatorServer) testEmbeddedByValue()                          {}

// UnsafeCustomCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomCalculatorServer will
// result in compilation errors.
type UnsafeCustomCalculatorServer interface {
	mustEmbedUnimplementedCustomCalculatorServer()
}

func RegisterCustomCalculatorServer(s grpc.ServiceRegistrar, srv CustomCalculatorServer) {
	// If the following call pancis, it indicates UnimplementedCustomCalculatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomCalculator_ServiceDesc, srv)
}

func _CustomCalculator_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomCalculatorServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomCalculator_Calculate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomCalculatorServer).Calculate(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomCalculator_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomCalculatorServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomCalculator_Multiply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomCalculatorServer).Multiply(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomCalculator_ServiceDesc is the grpc.ServiceDesc for CustomCalculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomCalculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "myservice.CustomCalculator",
	HandlerType: (*CustomCalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _CustomCalculator_Calculate_Handler,
		},
		{
			MethodName: "Multiply",
			Handler:    _CustomCalculator_Multiply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contract.proto",
}
